/**
 * Created by Prashanth Molakala on 8/3/2016.
 */

(function () {
  'use strict';

  angular
    .module('movieFlixUi')
    .service('movies', movies);

  /** @ngInject */
  function movies($resource, api) {
    var data = [
      {
        "_id": "578d50a3b64e55bc04a70f2a",
        "updatedAt": "2016-07-18T21:56:51.563Z",
        "createdAt": "2016-07-18T21:56:51.563Z",
        "Title": "The Newsroom",
        "Year": "2012â€“2014",
        "Rated": "TV-MA",
        "Released": "24 Jun 2012",
        "Runtime": "55 min",
        "Genre": "Drama",
        "Director": "N/A",
        "Writer": "Aaron Sorkin",
        "Actors": "Jeff Daniels, Emily Mortimer, John Gallagher Jr., Alison Pill",
        "Plot": "A newsroom undergoes some changes in its workings and morals as a new team is brought in, bringing unexpected results for its existing news anchor.",
        "Language": "English",
        "Country": "USA",
        "Awards": "Nominated for 2 Golden Globes. Another 8 wins & 29 nominations.",
        "Poster": "http://ia.media-imdb.com/images/M/MV5BMTEyMzc0ODAwMjVeQTJeQWpwZ15BbWU4MDMxODk4OTIx._V1_SX300.jpg",
        "Metascore": "N/A",
        "imdbRating": "8.6",
        "imdbVotes": "75,442",
        "imdbID": "tt1870479",
        "Type": "series",
        "__v": 0,
        "Reviews": []
      },
      {
        "_id": "578d50a3b64e55bc04a70f0c",
        "updatedAt": "2016-07-18T21:56:51.552Z",
        "createdAt": "2016-07-18T21:56:51.552Z",
        "Title": "The Grand Budapest Hotel",
        "Year": "2014",
        "Rated": "R",
        "Released": "28 Mar 2014",
        "Runtime": "99 min",
        "Genre": "Adventure, Comedy, Drama",
        "Director": "Wes Anderson",
        "Writer": "Stefan Zweig (inspired by the writings of), Wes Anderson (screenplay), Wes Anderson (story), Hugo Guinness (story)",
        "Actors": "Ralph Fiennes, F. Murray Abraham, Mathieu Amalric, Adrien Brody",
        "Plot": "The adventures of Gustave H, a legendary concierge at a famous hotel from the fictional Republic of Zubrowka between the first and second World Wars, and Zero Moustafa, the lobby boy who becomes his most trusted friend.",
        "Language": "English, French",
        "Country": "USA, Germany, UK",
        "Awards": "Won 4 Oscars. Another 115 wins & 204 nominations.",
        "Poster": "http://ia.media-imdb.com/images/M/MV5BMzM5NjUxOTEyMl5BMl5BanBnXkFtZTgwNjEyMDM0MDE@._V1_SX300.jpg",
        "Metascore": "88",
        "imdbRating": "8.1",
        "imdbVotes": "423,004",
        "imdbID": "tt2278388",
        "Type": "movie",
        "__v": 0,
        "Reviews": []
      },
      {
        "_id": "578d50a3b64e55bc04a70f17",
        "updatedAt": "2016-07-18T21:56:51.555Z",
        "createdAt": "2016-07-18T21:56:51.555Z",
        "Title": "The Vampire Diaries",
        "Year": "2009â€“",
        "Rated": "TV-14",
        "Released": "10 Sep 2009",
        "Runtime": "43 min",
        "Genre": "Drama, Fantasy, Horror",
        "Director": "N/A",
        "Writer": "Julie Plec, Kevin Williamson",
        "Actors": "Paul Wesley, Ian Somerhalder, Kat Graham, Candice King",
        "Plot": "A teenage girl is torn between two vampire brothers.",
        "Language": "English",
        "Country": "USA",
        "Awards": "35 wins & 48 nominations.",
        "Poster": "http://ia.media-imdb.com/images/M/MV5BMTgzMzg3NDMxOF5BMl5BanBnXkFtZTgwNjUwMjQyNzE@._V1_SX300.jpg",
        "Metascore": "N/A",
        "imdbRating": "7.9",
        "imdbVotes": "206,717",
        "imdbID": "tt1405406",
        "Type": "series",
        "__v": 0,
        "Reviews": []
      },
      {
        "_id": "578d50a3b64e55bc04a70f18",
        "updatedAt": "2016-07-18T21:56:51.556Z",
        "createdAt": "2016-07-18T21:56:51.556Z",
        "Title": "Friends",
        "Year": "1994â€“2004",
        "Rated": "TV-14",
        "Released": "22 Sep 1994",
        "Runtime": "22 min",
        "Genre": "Comedy, Romance",
        "Director": "N/A",
        "Writer": "David Crane, Marta Kauffman",
        "Actors": "Jennifer Aniston, Courteney Cox, Lisa Kudrow, Matt LeBlanc",
        "Plot": "Follows the lives of six 20-something friends living in Manhattan.",
        "Language": "English",
        "Country": "USA",
        "Awards": "Won 1 Golden Globe. Another 68 wins & 204 nominations.",
        "Poster": "http://ia.media-imdb.com/images/M/MV5BMTg4NzEyNzQ5OF5BMl5BanBnXkFtZTYwNTY3NDg4._V1._CR24,0,293,443_SX89_AL_.jpg_V1_SX300.jpg",
        "Metascore": "N/A",
        "imdbRating": "9.0",
        "imdbVotes": "433,690",
        "imdbID": "tt0108778",
        "Type": "series",
        "__v": 0,
        "Reviews": []
      },
      {
        "_id": "578d50a3b64e55bc04a70f19",
        "updatedAt": "2016-07-18T21:56:51.556Z",
        "createdAt": "2016-07-18T21:56:51.556Z",
        "Title": "Orange Is the New Black",
        "Year": "2013â€“",
        "Rated": "TV-MA",
        "Released": "11 Jul 2013",
        "Runtime": "59 min",
        "Genre": "Comedy, Crime, Drama",
        "Director": "N/A",
        "Writer": "N/A",
        "Actors": "Taylor Schilling, Michael Harney, Kate Mulgrew, Danielle Brooks",
        "Plot": "The story of Piper Chapman, a woman in her thirties who is sentenced to fifteen months in prison after being convicted of a decade-old crime of transporting money to her drug-dealing girlfriend.",
        "Language": "English",
        "Country": "USA",
        "Awards": "Nominated for 6 Golden Globes. Another 33 wins & 77 nominations.",
        "Poster": "http://ia.media-imdb.com/images/M/MV5BODQ2NjE2NDY3Ml5BMl5BanBnXkFtZTgwNjQxNzA1NTE@._V1_SX300.jpg",
        "Metascore": "N/A",
        "imdbRating": "8.3",
        "imdbVotes": "167,631",
        "imdbID": "tt2372162",
        "Type": "series",
        "__v": 0,
        "Reviews": []
      },
      {
        "_id": "578d50a3b64e55bc04a70ef4",
        "updatedAt": "2016-07-18T21:56:51.541Z",
        "createdAt": "2016-07-18T21:56:51.541Z",
        "Title": "Guardians of the Galaxy",
        "Year": "2014",
        "Rated": "PG-13",
        "Released": "01 Aug 2014",
        "Runtime": "121 min",
        "Genre": "Action, Adventure, Sci-Fi",
        "Director": "James Gunn",
        "Writer": "James Gunn, Nicole Perlman, Dan Abnett (comic book), Andy Lanning (comic book)",
        "Actors": "Chris Pratt, Zoe Saldana, Dave Bautista, Vin Diesel",
        "Plot": "A group of intergalactic criminals are forced to work together to stop a fanatical warrior from taking control of the universe.",
        "Language": "English",
        "Country": "USA, UK",
        "Awards": "Nominated for 2 Oscars. Another 45 wins & 87 nominations.",
        "Poster": "http://ia.media-imdb.com/images/M/MV5BMTAwMjU5OTgxNjZeQTJeQWpwZ15BbWU4MDUxNDYxODEx._V1_SX300.jpg",
        "Metascore": "76",
        "imdbRating": "8.1",
        "imdbVotes": "606,903",
        "imdbID": "tt2015381",
        "Type": "movie",
        "__v": 0,
        "Reviews": []
      },
      {
        "_id": "578d50a3b64e55bc04a70ef5",
        "updatedAt": "2016-07-18T21:56:51.541Z",
        "createdAt": "2016-07-18T21:56:51.541Z",
        "Title": "Inception",
        "Year": "2010",
        "Rated": "PG-13",
        "Released": "16 Jul 2010",
        "Runtime": "148 min",
        "Genre": "Action, Mystery, Sci-Fi",
        "Director": "Christopher Nolan",
        "Writer": "Christopher Nolan",
        "Actors": "Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen Page, Tom Hardy",
        "Plot": "A thief who steals corporate secrets through use of the dream-sharing technology is given the inverse task of planting an idea into the mind of a CEO.",
        "Language": "English, Japanese, French",
        "Country": "USA, UK",
        "Awards": "Won 4 Oscars. Another 138 wins & 192 nominations.",
        "Poster": "http://ia.media-imdb.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_SX300.jpg",
        "Metascore": "74",
        "imdbRating": "8.8",
        "imdbVotes": "1,366,602",
        "imdbID": "tt1375666",
        "Type": "movie",
        "__v": 0,
        "Reviews": []
      },
      {
        "_id": "578d50a3b64e55bc04a70ef6",
        "updatedAt": "2016-07-18T21:56:51.542Z",
        "createdAt": "2016-07-18T21:56:51.542Z",
        "Title": "The Walk",
        "Year": "2015",
        "Rated": "PG",
        "Released": "09 Oct 2015",
        "Runtime": "123 min",
        "Genre": "Adventure, Biography, Drama",
        "Director": "Robert Zemeckis",
        "Writer": "Robert Zemeckis (screenplay), Christopher Browne (screenplay), Philippe Petit (book)",
        "Actors": "Joseph Gordon-Levitt, Guillaume Baillargeon, Ã‰milie Leclerc, Mark Trafford",
        "Plot": "In 1974, high-wire artist Philippe Petit recruits a team of people to help him realize his dream: to walk the immense void between the World Trade Center towers.",
        "Language": "English, French",
        "Country": "USA",
        "Awards": "1 win & 9 nominations.",
        "Poster": "http://ia.media-imdb.com/images/M/MV5BNTY4MzA4Mzc5Nl5BMl5BanBnXkFtZTgwNDIzMzk5NjE@._V1_SX300.jpg",
        "Metascore": "70",
        "imdbRating": "7.5",
        "imdbVotes": "47,717",
        "imdbID": "tt3488710",
        "Type": "movie",
        "__v": 0,
        "Reviews": []
      },
      {
        "_id": "578d50a3b64e55bc04a70ef8",
        "updatedAt": "2016-07-18T21:56:51.543Z",
        "createdAt": "2016-07-18T21:56:51.543Z",
        "Title": "Schindler's List",
        "Year": "1993",
        "Rated": "R",
        "Released": "04 Feb 1994",
        "Runtime": "195 min",
        "Genre": "Biography, Drama, History",
        "Director": "Steven Spielberg",
        "Writer": "Thomas Keneally (book), Steven Zaillian (screenplay)",
        "Actors": "Liam Neeson, Ben Kingsley, Ralph Fiennes, Caroline Goodall",
        "Plot": "In Poland during World War II, Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis.",
        "Language": "English, Hebrew, German, Polish",
        "Country": "USA",
        "Awards": "Won 7 Oscars. Another 69 wins & 32 nominations.",
        "Poster": "http://ia.media-imdb.com/images/M/MV5BMzMwMTM4MDU2N15BMl5BanBnXkFtZTgwMzQ0MjMxMDE@._V1_SX300.jpg",
        "Metascore": "93",
        "imdbRating": "8.9",
        "imdbVotes": "808,194",
        "imdbID": "tt0108052",
        "Type": "movie",
        "__v": 0,
        "Reviews": []
      },
      {
        "_id": "578d50a3b64e55bc04a70eeb",
        "updatedAt": "2016-07-18T21:56:51.535Z",
        "createdAt": "2016-07-18T21:56:51.535Z",
        "Title": "Star Wars: The Force Awakens",
        "Year": "2015",
        "Rated": "PG-13",
        "Released": "18 Dec 2015",
        "Runtime": "135 min",
        "Genre": "Action, Adventure, Fantasy",
        "Director": "J.J. Abrams",
        "Writer": "Lawrence Kasdan, J.J. Abrams, Michael Arndt, George Lucas (based on characters created by)",
        "Actors": "Harrison Ford, Mark Hamill, Carrie Fisher, Adam Driver",
        "Plot": "Three decades after the defeat of the Galactic Empire, a new threat arises. The First Order attempts to rule the galaxy and only a ragtag group of heroes can stop them, along with the help of the Resistance.",
        "Language": "English",
        "Country": "USA",
        "Awards": "Nominated for 5 Oscars. Another 2 wins & 25 nominations.",
        "Poster": "http://ia.media-imdb.com/images/M/MV5BOTAzODEzNDAzMl5BMl5BanBnXkFtZTgwMDU1MTgzNzE@._V1_SX300.jpg",
        "Metascore": "81",
        "imdbRating": "8.4",
        "imdbVotes": "390,401",
        "imdbID": "tt2488496",
        "Type": "movie",
        "__v": 0,
        "Reviews": []
      },
      {
        "_id": "578d50a3b64e55bc04a70ef9",
        "updatedAt": "2016-07-18T21:56:51.543Z",
        "createdAt": "2016-07-18T21:56:51.543Z",
        "Title": "The Lord of the Rings: The Return of the King",
        "Year": "2003",
        "Rated": "PG-13",
        "Released": "17 Dec 2003",
        "Runtime": "201 min",
        "Genre": "Adventure, Drama, Fantasy",
        "Director": "Peter Jackson",
        "Writer": "J.R.R. Tolkien (novel), Fran Walsh (screenplay), Philippa Boyens (screenplay), Peter Jackson (screenplay)",
        "Actors": "Noel Appleby, Ali Astin, Sean Astin, David Aston",
        "Plot": "Gandalf and Aragorn lead the World of Men against Sauron's army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.",
        "Language": "English, Quenya, Old English, Sindarin",
        "Country": "USA, New Zealand",
        "Awards": "Won 11 Oscars. Another 158 wins & 107 nominations.",
        "Poster": "http://ia.media-imdb.com/images/M/MV5BMjE4MjA1NTAyMV5BMl5BanBnXkFtZTcwNzM1NDQyMQ@@._V1_SX300.jpg",
        "Metascore": "94",
        "imdbRating": "8.9",
        "imdbVotes": "1,147,689",
        "imdbID": "tt0167260",
        "Type": "movie",
        "__v": 0,
        "Reviews": []
      },
      {
        "_id": "578d50a3b64e55bc04a70efa",
        "updatedAt": "2016-07-18T21:56:51.544Z",
        "createdAt": "2016-07-18T21:56:51.544Z",
        "Title": "Fight Club",
        "Year": "1999",
        "Rated": "R",
        "Released": "15 Oct 1999",
        "Runtime": "139 min",
        "Genre": "Drama",
        "Director": "David Fincher",
        "Writer": "Chuck Palahniuk (novel), Jim Uhls (screenplay)",
        "Actors": "Edward Norton, Brad Pitt, Helena Bonham Carter, Meat Loaf",
        "Plot": "An insomniac office worker, looking for a way to change his life, crosses paths with a devil-may-care soap maker, forming an underground fight club that evolves into something much, much more...",
        "Language": "English",
        "Country": "USA, Germany",
        "Awards": "Nominated for 1 Oscar. Another 8 wins & 27 nominations.",
        "Poster": "http://ia.media-imdb.com/images/M/MV5BMjIwNTYzMzE1M15BMl5BanBnXkFtZTcwOTE5Mzg3OA@@._V1_SX300.jpg",
        "Metascore": "66",
        "imdbRating": "8.8",
        "imdbVotes": "1,254,308",
        "imdbID": "tt0137523",
        "Type": "movie",
        "__v": 0,
        "Reviews": []
      },
      {
        "_id": "578d50a3b64e55bc04a70efb",
        "updatedAt": "2016-07-18T21:56:51.544Z",
        "createdAt": "2016-07-18T21:56:51.544Z",
        "Title": "The Lord of the Rings: The Fellowship of the Ring",
        "Year": "2001",
        "Rated": "PG-13",
        "Released": "19 Dec 2001",
        "Runtime": "178 min",
        "Genre": "Adventure, Drama, Fantasy",
        "Director": "Peter Jackson",
        "Writer": "J.R.R. Tolkien (novel), Fran Walsh (screenplay), Philippa Boyens (screenplay), Peter Jackson (screenplay)",
        "Actors": "Alan Howard, Noel Appleby, Sean Astin, Sala Baker",
        "Plot": "A meek Hobbit and eight companions set out on a journey to destroy the One Ring and the Dark Lord Sauron.",
        "Language": "English, Sindarin",
        "Country": "New Zealand, USA",
        "Awards": "Won 4 Oscars. Another 101 wins & 111 nominations.",
        "Poster": "http://ia.media-imdb.com/images/M/MV5BNTEyMjAwMDU1OV5BMl5BanBnXkFtZTcwNDQyNTkxMw@@._V1_SX300.jpg",
        "Metascore": "92",
        "imdbRating": "8.8",
        "imdbVotes": "1,160,499",
        "imdbID": "tt0120737",
        "Type": "movie",
        "__v": 0,
        "Reviews": []
      },
      {
        "_id": "578d50a3b64e55bc04a70efc",
        "updatedAt": "2016-07-18T21:56:51.545Z",
        "createdAt": "2016-07-18T21:56:51.545Z",
        "Title": "Forrest Gump",
        "Year": "1994",
        "Rated": "PG-13",
        "Released": "06 Jul 1994",
        "Runtime": "142 min",
        "Genre": "Drama, Romance",
        "Director": "Robert Zemeckis",
        "Writer": "Winston Groom (novel), Eric Roth (screenplay)",
        "Actors": "Tom Hanks, Rebecca Williams, Sally Field, Michael Conner Humphreys",
        "Plot": "Forrest Gump, while not intelligent, has accidentally been present at many historic moments, but his true love, Jenny Curran, eludes him.",
        "Language": "English",
        "Country": "USA",
        "Awards": "Won 6 Oscars. Another 37 wins & 51 nominations.",
        "Poster": "http://ia.media-imdb.com/images/M/MV5BMTI1Nzk1MzQwMV5BMl5BanBnXkFtZTYwODkxOTA5._V1_SX300.jpg",
        "Metascore": "82",
        "imdbRating": "8.8",
        "imdbVotes": "1,167,104",
        "imdbID": "tt0109830",
        "Type": "movie",
        "__v": 0,
        "Reviews": []
      },
      {
        "_id": "578d50a3b64e55bc04a70efe",
        "updatedAt": "2016-07-18T21:56:51.546Z",
        "createdAt": "2016-07-18T21:56:51.546Z",
        "Title": "The Matrix",
        "Year": "1999",
        "Rated": "R",
        "Released": "31 Mar 1999",
        "Runtime": "136 min",
        "Genre": "Action, Sci-Fi",
        "Director": "Andy Wachowski, Lana Wachowski",
        "Writer": "Andy Wachowski, Lana Wachowski",
        "Actors": "Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss, Hugo Weaving",
        "Plot": "A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.",
        "Language": "English",
        "Country": "USA, Australia",
        "Awards": "Won 4 Oscars. Another 33 wins & 42 nominations.",
        "Poster": "http://ia.media-imdb.com/images/M/MV5BMTkxNDYxOTA4M15BMl5BanBnXkFtZTgwNTk0NzQxMTE@._V1_SX300.jpg",
        "Metascore": "73",
        "imdbRating": "8.7",
        "imdbVotes": "1,148,739",
        "imdbID": "tt0133093",
        "Type": "movie",
        "__v": 0,
        "Reviews": []
      },
      {
        "_id": "578d50a3b64e55bc04a70f00",
        "updatedAt": "2016-07-18T21:56:51.546Z",
        "createdAt": "2016-07-18T21:56:51.546Z",
        "Title": "Django Unchained",
        "Year": "2012",
        "Rated": "R",
        "Released": "25 Dec 2012",
        "Runtime": "165 min",
        "Genre": "Drama, Western",
        "Director": "Quentin Tarantino",
        "Writer": "Quentin Tarantino",
        "Actors": "Jamie Foxx, Christoph Waltz, Leonardo DiCaprio, Kerry Washington",
        "Plot": "With the help of a German bounty hunter, a freed slave sets out to rescue his wife from a brutal Mississippi plantation owner.",
        "Language": "English, German, French",
        "Country": "USA",
        "Awards": "Won 2 Oscars. Another 51 wins & 133 nominations.",
        "Poster": "http://ia.media-imdb.com/images/M/MV5BMjIyNTQ5NjQ1OV5BMl5BanBnXkFtZTcwODg1MDU4OA@@._V1_SX300.jpg",
        "Metascore": "81",
        "imdbRating": "8.5",
        "imdbVotes": "870,792",
        "imdbID": "tt1853728",
        "Type": "movie",
        "__v": 0,
        "Reviews": []
      },
      {
        "_id": "578d50a3b64e55bc04a70f01",
        "updatedAt": "2016-07-18T21:56:51.548Z",
        "createdAt": "2016-07-18T21:56:51.548Z",
        "Title": "Braveheart",
        "Year": "1995",
        "Rated": "R",
        "Released": "24 May 1995",
        "Runtime": "178 min",
        "Genre": "Biography, Drama, History",
        "Director": "Mel Gibson",
        "Writer": "Randall Wallace",
        "Actors": "James Robinson, Sean Lawlor, Sandy Nelson, James Cosmo",
        "Plot": "When his secret bride is executed for assaulting an English soldier who tried to rape her, William Wallace begins a revolt and leads Scottish warriors against the cruel English tyrant who rules Scotland with an iron fist.",
        "Language": "English, French, Latin, Scottish Gaelic",
        "Country": "USA",
        "Awards": "Won 5 Oscars. Another 25 wins & 27 nominations.",
        "Poster": "http://ia.media-imdb.com/images/M/MV5BNjA4ODYxMDU3Nl5BMl5BanBnXkFtZTcwMzkzMTk3OA@@._V1_SX300.jpg",
        "Metascore": "68",
        "imdbRating": "8.4",
        "imdbVotes": "694,585",
        "imdbID": "tt0112573",
        "Type": "movie",
        "__v": 0,
        "Reviews": []
      },
      {
        "_id": "578d50a3b64e55bc04a70ef0",
        "updatedAt": "2016-07-18T21:56:51.538Z",
        "createdAt": "2016-07-18T21:56:51.538Z",
        "Title": "The Godfather",
        "Year": "1972",
        "Rated": "R",
        "Released": "24 Mar 1972",
        "Runtime": "175 min",
        "Genre": "Crime, Drama",
        "Director": "Francis Ford Coppola",
        "Writer": "Mario Puzo (screenplay), Francis Ford Coppola (screenplay), Mario Puzo (novel)",
        "Actors": "Marlon Brando, Al Pacino, James Caan, Richard S. Castellano",
        "Plot": "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
        "Language": "English, Italian, Latin",
        "Country": "USA",
        "Awards": "Won 3 Oscars. Another 23 wins & 27 nominations.",
        "Poster": "http://ia.media-imdb.com/images/M/MV5BMjEyMjcyNDI4MF5BMl5BanBnXkFtZTcwMDA5Mzg3OA@@._V1_SX300.jpg",
        "Metascore": "100",
        "imdbRating": "9.2",
        "imdbVotes": "1,085,001",
        "imdbID": "tt0068646",
        "Type": "movie",
        "__v": 0,
        "Reviews": []
      }
    ];

    this.getLocalMovies = getLocalMovies;
    this.getApiMovies = getApiMovies;
    this.getReviews = getReviews;

    function getLocalMovies() {
      return data;
    }

    function getApiMovies() {
      return $resource(api + "movies/:id", null,
        {
          'update': {
            method: 'PUT'
          }
        });
    }

    function getReviews() {
      return $resource(api + 'movies/:id/reviews/:reviewId', null,
        {
          'update': {
            method: 'PUT'
          }
        });
    }

  }
})();
